name: CI

on:
  push:
    branches:
      - js

env:
  CF_ACCOUNT_ID: c6b0fe2afa4b4d09801e9d18c859da8d
  PAGES_PROJECT_NAME: sequelize-ui

jobs:
  deploy-legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy legacy
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: "${{ env.CF_ACCOUNT_ID }}"
          project-name: "${{ env.PAGES_PROJECT_NAME }}"
          api-key: "${{ secrets.CF_GLOBAL_APIKEY }}"
          email: "${{ secrets.CF_EMAIL }}"
          branch: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
